files: \.(py|yaml|txt)$
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
    - id: ruff
      args: [--fix, --target-version, "py311", --select, "ALL", --ignore, "ANN,C90,D,E501,PT,T20,Q,SLF"]

